base=eval(input("Enter base value "))
power=eval(input("Enter power value "))
pow_1=base**power
pwo_2=pow(base,power)
print(" To display the value of the base raised to that exponent ")
print("What base ? ",base)
print("What power of",base,"?",power)
print("\n")
print("Method 1 ")
print(base," to the power of ",power," is ",pow_1)
print("\n")
print("Method 2 ")
print(base," to the power of ",power," is ",pwo_2)
